/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SerialRouteImport } from './routes/serial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesArticleSlugRouteImport } from './routes/articles/$articleSlug'
import { Route as IssuesSerialYoucantwisttimeRouteImport } from './routes/Issues/serial/youcantwisttime'
import { Route as IssuesSerialWesternRouteImport } from './routes/Issues/serial/western'
import { Route as IssuesSerialStomachacheRouteImport } from './routes/Issues/serial/stomachache'
import { Route as IssuesSerialLifeinparadiseRouteImport } from './routes/Issues/serial/lifeinparadise'
import { Route as IssuesSerialKeyboardsRouteImport } from './routes/Issues/serial/keyboards'
import { Route as IssuesSerialIndigoosRouteImport } from './routes/Issues/serial/indigoos'
import { Route as IssuesSerialIloveshoppingRouteImport } from './routes/Issues/serial/iloveshopping'
import { Route as IssuesSerialCovetRouteImport } from './routes/Issues/serial/covet'
import { Route as IssuesSerialAnumberoutofplaceRouteImport } from './routes/Issues/serial/anumberoutofplace'

const SerialRoute = SerialRouteImport.update({
  id: '/serial',
  path: '/serial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleSlugRoute = ArticlesArticleSlugRouteImport.update({
  id: '/articles/$articleSlug',
  path: '/articles/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialYoucantwisttimeRoute =
  IssuesSerialYoucantwisttimeRouteImport.update({
    id: '/Issues/serial/youcantwisttime',
    path: '/Issues/serial/youcantwisttime',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesSerialWesternRoute = IssuesSerialWesternRouteImport.update({
  id: '/Issues/serial/western',
  path: '/Issues/serial/western',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialStomachacheRoute = IssuesSerialStomachacheRouteImport.update({
  id: '/Issues/serial/stomachache',
  path: '/Issues/serial/stomachache',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialLifeinparadiseRoute =
  IssuesSerialLifeinparadiseRouteImport.update({
    id: '/Issues/serial/lifeinparadise',
    path: '/Issues/serial/lifeinparadise',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesSerialKeyboardsRoute = IssuesSerialKeyboardsRouteImport.update({
  id: '/Issues/serial/keyboards',
  path: '/Issues/serial/keyboards',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialIndigoosRoute = IssuesSerialIndigoosRouteImport.update({
  id: '/Issues/serial/indigoos',
  path: '/Issues/serial/indigoos',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialIloveshoppingRoute =
  IssuesSerialIloveshoppingRouteImport.update({
    id: '/Issues/serial/iloveshopping',
    path: '/Issues/serial/iloveshopping',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesSerialCovetRoute = IssuesSerialCovetRouteImport.update({
  id: '/Issues/serial/covet',
  path: '/Issues/serial/covet',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialAnumberoutofplaceRoute =
  IssuesSerialAnumberoutofplaceRouteImport.update({
    id: '/Issues/serial/anumberoutofplace',
    path: '/Issues/serial/anumberoutofplace',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/serial': typeof SerialRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/serial': typeof SerialRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/serial': typeof SerialRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/serial'
    | '/articles/$articleSlug'
    | '/articles'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/serial'
    | '/articles/$articleSlug'
    | '/articles'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
  id:
    | '__root__'
    | '/'
    | '/serial'
    | '/articles/$articleSlug'
    | '/articles/'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SerialRoute: typeof SerialRoute
  ArticlesArticleSlugRoute: typeof ArticlesArticleSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  IssuesSerialAnumberoutofplaceRoute: typeof IssuesSerialAnumberoutofplaceRoute
  IssuesSerialCovetRoute: typeof IssuesSerialCovetRoute
  IssuesSerialIloveshoppingRoute: typeof IssuesSerialIloveshoppingRoute
  IssuesSerialIndigoosRoute: typeof IssuesSerialIndigoosRoute
  IssuesSerialKeyboardsRoute: typeof IssuesSerialKeyboardsRoute
  IssuesSerialLifeinparadiseRoute: typeof IssuesSerialLifeinparadiseRoute
  IssuesSerialStomachacheRoute: typeof IssuesSerialStomachacheRoute
  IssuesSerialWesternRoute: typeof IssuesSerialWesternRoute
  IssuesSerialYoucantwisttimeRoute: typeof IssuesSerialYoucantwisttimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/serial': {
      id: '/serial'
      path: '/serial'
      fullPath: '/serial'
      preLoaderRoute: typeof SerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleSlug': {
      id: '/articles/$articleSlug'
      path: '/articles/$articleSlug'
      fullPath: '/articles/$articleSlug'
      preLoaderRoute: typeof ArticlesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/youcantwisttime': {
      id: '/Issues/serial/youcantwisttime'
      path: '/Issues/serial/youcantwisttime'
      fullPath: '/Issues/serial/youcantwisttime'
      preLoaderRoute: typeof IssuesSerialYoucantwisttimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/western': {
      id: '/Issues/serial/western'
      path: '/Issues/serial/western'
      fullPath: '/Issues/serial/western'
      preLoaderRoute: typeof IssuesSerialWesternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/stomachache': {
      id: '/Issues/serial/stomachache'
      path: '/Issues/serial/stomachache'
      fullPath: '/Issues/serial/stomachache'
      preLoaderRoute: typeof IssuesSerialStomachacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/lifeinparadise': {
      id: '/Issues/serial/lifeinparadise'
      path: '/Issues/serial/lifeinparadise'
      fullPath: '/Issues/serial/lifeinparadise'
      preLoaderRoute: typeof IssuesSerialLifeinparadiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/keyboards': {
      id: '/Issues/serial/keyboards'
      path: '/Issues/serial/keyboards'
      fullPath: '/Issues/serial/keyboards'
      preLoaderRoute: typeof IssuesSerialKeyboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/indigoos': {
      id: '/Issues/serial/indigoos'
      path: '/Issues/serial/indigoos'
      fullPath: '/Issues/serial/indigoos'
      preLoaderRoute: typeof IssuesSerialIndigoosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/iloveshopping': {
      id: '/Issues/serial/iloveshopping'
      path: '/Issues/serial/iloveshopping'
      fullPath: '/Issues/serial/iloveshopping'
      preLoaderRoute: typeof IssuesSerialIloveshoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/covet': {
      id: '/Issues/serial/covet'
      path: '/Issues/serial/covet'
      fullPath: '/Issues/serial/covet'
      preLoaderRoute: typeof IssuesSerialCovetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/anumberoutofplace': {
      id: '/Issues/serial/anumberoutofplace'
      path: '/Issues/serial/anumberoutofplace'
      fullPath: '/Issues/serial/anumberoutofplace'
      preLoaderRoute: typeof IssuesSerialAnumberoutofplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SerialRoute: SerialRoute,
  ArticlesArticleSlugRoute: ArticlesArticleSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  IssuesSerialAnumberoutofplaceRoute: IssuesSerialAnumberoutofplaceRoute,
  IssuesSerialCovetRoute: IssuesSerialCovetRoute,
  IssuesSerialIloveshoppingRoute: IssuesSerialIloveshoppingRoute,
  IssuesSerialIndigoosRoute: IssuesSerialIndigoosRoute,
  IssuesSerialKeyboardsRoute: IssuesSerialKeyboardsRoute,
  IssuesSerialLifeinparadiseRoute: IssuesSerialLifeinparadiseRoute,
  IssuesSerialStomachacheRoute: IssuesSerialStomachacheRoute,
  IssuesSerialWesternRoute: IssuesSerialWesternRoute,
  IssuesSerialYoucantwisttimeRoute: IssuesSerialYoucantwisttimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
