/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualArtsRouteImport } from './routes/visual-arts'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PhotoboothRouteImport } from './routes/photobooth'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as IssuesIndexRouteImport } from './routes/Issues/index'
import { Route as DevVictorianRouteImport } from './routes/dev/victorian'
import { Route as ArticlesArticleSlugRouteImport } from './routes/articles/$articleSlug'
import { Route as IssuesSerialRouteImport } from './routes/Issues/serial'
import { Route as IssuesReminiscenceRouteImport } from './routes/Issues/reminiscence'
import { Route as IssuesNotRouteImport } from './routes/Issues/not'
import { Route as IssuesKismetRouteImport } from './routes/Issues/kismet'
import { Route as IssuesAndsceneRouteImport } from './routes/Issues/andscene'
import { Route as IssuesSerialIndexRouteImport } from './routes/Issues/serial/index'
import { Route as IssuesSerialYoucantwisttimeRouteImport } from './routes/Issues/serial/youcantwisttime'
import { Route as IssuesSerialWesternRouteImport } from './routes/Issues/serial/western'
import { Route as IssuesSerialStomachacheRouteImport } from './routes/Issues/serial/stomachache'
import { Route as IssuesSerialLifeinparadiseRouteImport } from './routes/Issues/serial/lifeinparadise'
import { Route as IssuesSerialKeyboardsRouteImport } from './routes/Issues/serial/keyboards'
import { Route as IssuesSerialIndigoosRouteImport } from './routes/Issues/serial/indigoos'
import { Route as IssuesSerialIloveshoppingRouteImport } from './routes/Issues/serial/iloveshopping'
import { Route as IssuesSerialCovetRouteImport } from './routes/Issues/serial/covet'
import { Route as IssuesSerialAnumberoutofplaceRouteImport } from './routes/Issues/serial/anumberoutofplace'
import { Route as IssuesAndsceneEternalunfoldingRouteImport } from './routes/Issues/andscene/eternalunfolding'

const VisualArtsRoute = VisualArtsRouteImport.update({
  id: '/visual-arts',
  path: '/visual-arts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoboothRoute = PhotoboothRouteImport.update({
  id: '/photobooth',
  path: '/photobooth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/Issues/',
  path: '/Issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevVictorianRoute = DevVictorianRouteImport.update({
  id: '/dev/victorian',
  path: '/dev/victorian',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleSlugRoute = ArticlesArticleSlugRouteImport.update({
  id: '/articles/$articleSlug',
  path: '/articles/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialRoute = IssuesSerialRouteImport.update({
  id: '/Issues/serial',
  path: '/Issues/serial',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesReminiscenceRoute = IssuesReminiscenceRouteImport.update({
  id: '/Issues/reminiscence',
  path: '/Issues/reminiscence',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesNotRoute = IssuesNotRouteImport.update({
  id: '/Issues/not',
  path: '/Issues/not',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesKismetRoute = IssuesKismetRouteImport.update({
  id: '/Issues/kismet',
  path: '/Issues/kismet',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesAndsceneRoute = IssuesAndsceneRouteImport.update({
  id: '/Issues/andscene',
  path: '/Issues/andscene',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSerialIndexRoute = IssuesSerialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialYoucantwisttimeRoute =
  IssuesSerialYoucantwisttimeRouteImport.update({
    id: '/youcantwisttime',
    path: '/youcantwisttime',
    getParentRoute: () => IssuesSerialRoute,
  } as any)
const IssuesSerialWesternRoute = IssuesSerialWesternRouteImport.update({
  id: '/western',
  path: '/western',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialStomachacheRoute = IssuesSerialStomachacheRouteImport.update({
  id: '/stomachache',
  path: '/stomachache',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialLifeinparadiseRoute =
  IssuesSerialLifeinparadiseRouteImport.update({
    id: '/lifeinparadise',
    path: '/lifeinparadise',
    getParentRoute: () => IssuesSerialRoute,
  } as any)
const IssuesSerialKeyboardsRoute = IssuesSerialKeyboardsRouteImport.update({
  id: '/keyboards',
  path: '/keyboards',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialIndigoosRoute = IssuesSerialIndigoosRouteImport.update({
  id: '/indigoos',
  path: '/indigoos',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialIloveshoppingRoute =
  IssuesSerialIloveshoppingRouteImport.update({
    id: '/iloveshopping',
    path: '/iloveshopping',
    getParentRoute: () => IssuesSerialRoute,
  } as any)
const IssuesSerialCovetRoute = IssuesSerialCovetRouteImport.update({
  id: '/covet',
  path: '/covet',
  getParentRoute: () => IssuesSerialRoute,
} as any)
const IssuesSerialAnumberoutofplaceRoute =
  IssuesSerialAnumberoutofplaceRouteImport.update({
    id: '/anumberoutofplace',
    path: '/anumberoutofplace',
    getParentRoute: () => IssuesSerialRoute,
  } as any)
const IssuesAndsceneEternalunfoldingRoute =
  IssuesAndsceneEternalunfoldingRouteImport.update({
    id: '/eternalunfolding',
    path: '/eternalunfolding',
    getParentRoute: () => IssuesAndsceneRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRoute
  '/newsletter': typeof NewsletterRoute
  '/photobooth': typeof PhotoboothRoute
  '/quiz': typeof QuizRoute
  '/visual-arts': typeof VisualArtsRoute
  '/Issues/andscene': typeof IssuesAndsceneRouteWithChildren
  '/Issues/kismet': typeof IssuesKismetRoute
  '/Issues/not': typeof IssuesNotRoute
  '/Issues/reminiscence': typeof IssuesReminiscenceRoute
  '/Issues/serial': typeof IssuesSerialRouteWithChildren
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/dev/victorian': typeof DevVictorianRoute
  '/Issues': typeof IssuesIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/Issues/andscene/eternalunfolding': typeof IssuesAndsceneEternalunfoldingRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
  '/Issues/serial/': typeof IssuesSerialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRoute
  '/newsletter': typeof NewsletterRoute
  '/photobooth': typeof PhotoboothRoute
  '/quiz': typeof QuizRoute
  '/visual-arts': typeof VisualArtsRoute
  '/Issues/andscene': typeof IssuesAndsceneRouteWithChildren
  '/Issues/kismet': typeof IssuesKismetRoute
  '/Issues/not': typeof IssuesNotRoute
  '/Issues/reminiscence': typeof IssuesReminiscenceRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/dev/victorian': typeof DevVictorianRoute
  '/Issues': typeof IssuesIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/Issues/andscene/eternalunfolding': typeof IssuesAndsceneEternalunfoldingRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
  '/Issues/serial': typeof IssuesSerialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRoute
  '/newsletter': typeof NewsletterRoute
  '/photobooth': typeof PhotoboothRoute
  '/quiz': typeof QuizRoute
  '/visual-arts': typeof VisualArtsRoute
  '/Issues/andscene': typeof IssuesAndsceneRouteWithChildren
  '/Issues/kismet': typeof IssuesKismetRoute
  '/Issues/not': typeof IssuesNotRoute
  '/Issues/reminiscence': typeof IssuesReminiscenceRoute
  '/Issues/serial': typeof IssuesSerialRouteWithChildren
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/dev/victorian': typeof DevVictorianRoute
  '/Issues/': typeof IssuesIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/Issues/andscene/eternalunfolding': typeof IssuesAndsceneEternalunfoldingRoute
  '/Issues/serial/anumberoutofplace': typeof IssuesSerialAnumberoutofplaceRoute
  '/Issues/serial/covet': typeof IssuesSerialCovetRoute
  '/Issues/serial/iloveshopping': typeof IssuesSerialIloveshoppingRoute
  '/Issues/serial/indigoos': typeof IssuesSerialIndigoosRoute
  '/Issues/serial/keyboards': typeof IssuesSerialKeyboardsRoute
  '/Issues/serial/lifeinparadise': typeof IssuesSerialLifeinparadiseRoute
  '/Issues/serial/stomachache': typeof IssuesSerialStomachacheRoute
  '/Issues/serial/western': typeof IssuesSerialWesternRoute
  '/Issues/serial/youcantwisttime': typeof IssuesSerialYoucantwisttimeRoute
  '/Issues/serial/': typeof IssuesSerialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/issues'
    | '/newsletter'
    | '/photobooth'
    | '/quiz'
    | '/visual-arts'
    | '/Issues/andscene'
    | '/Issues/kismet'
    | '/Issues/not'
    | '/Issues/reminiscence'
    | '/Issues/serial'
    | '/articles/$articleSlug'
    | '/dev/victorian'
    | '/Issues'
    | '/articles'
    | '/Issues/andscene/eternalunfolding'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
    | '/Issues/serial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/issues'
    | '/newsletter'
    | '/photobooth'
    | '/quiz'
    | '/visual-arts'
    | '/Issues/andscene'
    | '/Issues/kismet'
    | '/Issues/not'
    | '/Issues/reminiscence'
    | '/articles/$articleSlug'
    | '/dev/victorian'
    | '/Issues'
    | '/articles'
    | '/Issues/andscene/eternalunfolding'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
    | '/Issues/serial'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/issues'
    | '/newsletter'
    | '/photobooth'
    | '/quiz'
    | '/visual-arts'
    | '/Issues/andscene'
    | '/Issues/kismet'
    | '/Issues/not'
    | '/Issues/reminiscence'
    | '/Issues/serial'
    | '/articles/$articleSlug'
    | '/dev/victorian'
    | '/Issues/'
    | '/articles/'
    | '/Issues/andscene/eternalunfolding'
    | '/Issues/serial/anumberoutofplace'
    | '/Issues/serial/covet'
    | '/Issues/serial/iloveshopping'
    | '/Issues/serial/indigoos'
    | '/Issues/serial/keyboards'
    | '/Issues/serial/lifeinparadise'
    | '/Issues/serial/stomachache'
    | '/Issues/serial/western'
    | '/Issues/serial/youcantwisttime'
    | '/Issues/serial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IssuesRoute: typeof IssuesRoute
  NewsletterRoute: typeof NewsletterRoute
  PhotoboothRoute: typeof PhotoboothRoute
  QuizRoute: typeof QuizRoute
  VisualArtsRoute: typeof VisualArtsRoute
  IssuesAndsceneRoute: typeof IssuesAndsceneRouteWithChildren
  IssuesKismetRoute: typeof IssuesKismetRoute
  IssuesNotRoute: typeof IssuesNotRoute
  IssuesReminiscenceRoute: typeof IssuesReminiscenceRoute
  IssuesSerialRoute: typeof IssuesSerialRouteWithChildren
  ArticlesArticleSlugRoute: typeof ArticlesArticleSlugRoute
  DevVictorianRoute: typeof DevVictorianRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-arts': {
      id: '/visual-arts'
      path: '/visual-arts'
      fullPath: '/visual-arts'
      preLoaderRoute: typeof VisualArtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth': {
      id: '/photobooth'
      path: '/photobooth'
      fullPath: '/photobooth'
      preLoaderRoute: typeof PhotoboothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/': {
      id: '/Issues/'
      path: '/Issues'
      fullPath: '/Issues'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/victorian': {
      id: '/dev/victorian'
      path: '/dev/victorian'
      fullPath: '/dev/victorian'
      preLoaderRoute: typeof DevVictorianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleSlug': {
      id: '/articles/$articleSlug'
      path: '/articles/$articleSlug'
      fullPath: '/articles/$articleSlug'
      preLoaderRoute: typeof ArticlesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial': {
      id: '/Issues/serial'
      path: '/Issues/serial'
      fullPath: '/Issues/serial'
      preLoaderRoute: typeof IssuesSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/reminiscence': {
      id: '/Issues/reminiscence'
      path: '/Issues/reminiscence'
      fullPath: '/Issues/reminiscence'
      preLoaderRoute: typeof IssuesReminiscenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/not': {
      id: '/Issues/not'
      path: '/Issues/not'
      fullPath: '/Issues/not'
      preLoaderRoute: typeof IssuesNotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/kismet': {
      id: '/Issues/kismet'
      path: '/Issues/kismet'
      fullPath: '/Issues/kismet'
      preLoaderRoute: typeof IssuesKismetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/andscene': {
      id: '/Issues/andscene'
      path: '/Issues/andscene'
      fullPath: '/Issues/andscene'
      preLoaderRoute: typeof IssuesAndsceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Issues/serial/': {
      id: '/Issues/serial/'
      path: '/'
      fullPath: '/Issues/serial/'
      preLoaderRoute: typeof IssuesSerialIndexRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/youcantwisttime': {
      id: '/Issues/serial/youcantwisttime'
      path: '/youcantwisttime'
      fullPath: '/Issues/serial/youcantwisttime'
      preLoaderRoute: typeof IssuesSerialYoucantwisttimeRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/western': {
      id: '/Issues/serial/western'
      path: '/western'
      fullPath: '/Issues/serial/western'
      preLoaderRoute: typeof IssuesSerialWesternRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/stomachache': {
      id: '/Issues/serial/stomachache'
      path: '/stomachache'
      fullPath: '/Issues/serial/stomachache'
      preLoaderRoute: typeof IssuesSerialStomachacheRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/lifeinparadise': {
      id: '/Issues/serial/lifeinparadise'
      path: '/lifeinparadise'
      fullPath: '/Issues/serial/lifeinparadise'
      preLoaderRoute: typeof IssuesSerialLifeinparadiseRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/keyboards': {
      id: '/Issues/serial/keyboards'
      path: '/keyboards'
      fullPath: '/Issues/serial/keyboards'
      preLoaderRoute: typeof IssuesSerialKeyboardsRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/indigoos': {
      id: '/Issues/serial/indigoos'
      path: '/indigoos'
      fullPath: '/Issues/serial/indigoos'
      preLoaderRoute: typeof IssuesSerialIndigoosRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/iloveshopping': {
      id: '/Issues/serial/iloveshopping'
      path: '/iloveshopping'
      fullPath: '/Issues/serial/iloveshopping'
      preLoaderRoute: typeof IssuesSerialIloveshoppingRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/covet': {
      id: '/Issues/serial/covet'
      path: '/covet'
      fullPath: '/Issues/serial/covet'
      preLoaderRoute: typeof IssuesSerialCovetRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/serial/anumberoutofplace': {
      id: '/Issues/serial/anumberoutofplace'
      path: '/anumberoutofplace'
      fullPath: '/Issues/serial/anumberoutofplace'
      preLoaderRoute: typeof IssuesSerialAnumberoutofplaceRouteImport
      parentRoute: typeof IssuesSerialRoute
    }
    '/Issues/andscene/eternalunfolding': {
      id: '/Issues/andscene/eternalunfolding'
      path: '/eternalunfolding'
      fullPath: '/Issues/andscene/eternalunfolding'
      preLoaderRoute: typeof IssuesAndsceneEternalunfoldingRouteImport
      parentRoute: typeof IssuesAndsceneRoute
    }
  }
}

interface IssuesAndsceneRouteChildren {
  IssuesAndsceneEternalunfoldingRoute: typeof IssuesAndsceneEternalunfoldingRoute
}

const IssuesAndsceneRouteChildren: IssuesAndsceneRouteChildren = {
  IssuesAndsceneEternalunfoldingRoute: IssuesAndsceneEternalunfoldingRoute,
}

const IssuesAndsceneRouteWithChildren = IssuesAndsceneRoute._addFileChildren(
  IssuesAndsceneRouteChildren,
)

interface IssuesSerialRouteChildren {
  IssuesSerialAnumberoutofplaceRoute: typeof IssuesSerialAnumberoutofplaceRoute
  IssuesSerialCovetRoute: typeof IssuesSerialCovetRoute
  IssuesSerialIloveshoppingRoute: typeof IssuesSerialIloveshoppingRoute
  IssuesSerialIndigoosRoute: typeof IssuesSerialIndigoosRoute
  IssuesSerialKeyboardsRoute: typeof IssuesSerialKeyboardsRoute
  IssuesSerialLifeinparadiseRoute: typeof IssuesSerialLifeinparadiseRoute
  IssuesSerialStomachacheRoute: typeof IssuesSerialStomachacheRoute
  IssuesSerialWesternRoute: typeof IssuesSerialWesternRoute
  IssuesSerialYoucantwisttimeRoute: typeof IssuesSerialYoucantwisttimeRoute
  IssuesSerialIndexRoute: typeof IssuesSerialIndexRoute
}

const IssuesSerialRouteChildren: IssuesSerialRouteChildren = {
  IssuesSerialAnumberoutofplaceRoute: IssuesSerialAnumberoutofplaceRoute,
  IssuesSerialCovetRoute: IssuesSerialCovetRoute,
  IssuesSerialIloveshoppingRoute: IssuesSerialIloveshoppingRoute,
  IssuesSerialIndigoosRoute: IssuesSerialIndigoosRoute,
  IssuesSerialKeyboardsRoute: IssuesSerialKeyboardsRoute,
  IssuesSerialLifeinparadiseRoute: IssuesSerialLifeinparadiseRoute,
  IssuesSerialStomachacheRoute: IssuesSerialStomachacheRoute,
  IssuesSerialWesternRoute: IssuesSerialWesternRoute,
  IssuesSerialYoucantwisttimeRoute: IssuesSerialYoucantwisttimeRoute,
  IssuesSerialIndexRoute: IssuesSerialIndexRoute,
}

const IssuesSerialRouteWithChildren = IssuesSerialRoute._addFileChildren(
  IssuesSerialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IssuesRoute: IssuesRoute,
  NewsletterRoute: NewsletterRoute,
  PhotoboothRoute: PhotoboothRoute,
  QuizRoute: QuizRoute,
  VisualArtsRoute: VisualArtsRoute,
  IssuesAndsceneRoute: IssuesAndsceneRouteWithChildren,
  IssuesKismetRoute: IssuesKismetRoute,
  IssuesNotRoute: IssuesNotRoute,
  IssuesReminiscenceRoute: IssuesReminiscenceRoute,
  IssuesSerialRoute: IssuesSerialRouteWithChildren,
  ArticlesArticleSlugRoute: ArticlesArticleSlugRoute,
  DevVictorianRoute: DevVictorianRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
